# Generated by Django 4.1 on 2024-03-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0001_initial"),
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisedetails",
            name="exercise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exercises.exercise",
            ),
        ),
    ]
