# Generated by Django 4.1 on 2024-03-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("CH", "Chest"),
                            ("BK", "Back"),
                            ("TP", "Traps"),
                            ("CV", "Calves"),
                            ("QD", "Quads"),
                            ("HM", "Hamstrings"),
                            ("BC", "Biceps"),
                            ("TC", "Triceps"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("BW", "Body Weight"),
                            ("BB", "Barbell"),
                            ("DB", "Dumbbell"),
                            ("MC", "Machine"),
                            ("TM", "Treadmill"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                ("instructions", models.CharField(max_length=300)),
            ],
            options={
                "unique_together": {("name", "equipment", "muscle_group")},
            },
        ),
    ]
